# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{habitat}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ed Schmalzle"]
  s.date = %q{2010-08-04}
  s.description = %q{Automatically loads heroku config variables into your environment for development}
  s.email = %q{Jonas714@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "habitat.gemspec",
     "lib/habitat.rb",
     "lib/habitat/railtie.rb"
  ]
  s.homepage = %q{http://github.com/nerdEd/habitat}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Automatically loads heroku config variables into your environment for development}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<heroku>, [">= 1.8.3"])
    else
      s.add_dependency(%q<heroku>, [">= 1.8.3"])
    end
  else
    s.add_dependency(%q<heroku>, [">= 1.8.3"])
  end
end

